### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by EraZTeqZ** [R3DDY97/KICKthemOUT3#2]
I get this error when i start kick3.py with python3.4:

`Traceback (most recent call last):G 0N...
  File "./kick3.py", line 309, in <module>
    watson.scanNetwork()
  File "./kick3.py", line 66, in scanNetwork
    self.defaultGatewayIP = routing[1][2]
IndexError: list index out of range`

**Comment by R3DDY97** [comment]
@EraZTeqZ 
Changed the way of getting gateway IP and error is fixed now

**Comment by MiukkaZh** [comment]
I encountered this error when there are multiple hosts in the LAN
![qq 20180518224542](https://user-images.githubusercontent.com/32921723/40241303-3c956df2-5aed-11e8-8b5a-ac86efb251c0.png)

**Comment by R3DDY97** [comment]
@SasukeZhy 
It might be problem with getting vendor name form mac
U try running code again ..
it will try fetching vendor name
if it fails .. it return "NA"
